/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EducationLevel = { 'highSchool' : null } |
  { 'other' : null } |
  { 'undergraduate' : null } |
  { 'postgraduate' : null } |
  { 'doctorate' : null };
export interface Enquiry {
  'id' : EnquiryId,
  'inquiryType' : InquiryType,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
  'programType' : ProgramType,
  'educationLevel' : EducationLevel,
  'countryPreference' : string,
}
export type EnquiryId = bigint;
export interface EnquiryInput {
  'inquiryType' : InquiryType,
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
  'programType' : ProgramType,
  'educationLevel' : EducationLevel,
  'countryPreference' : string,
}
export type InquiryType = { 'patents' : null } |
  { 'studyAbroad' : null } |
  { 'other' : null } |
  { 'thesisWriting' : null } |
  { 'onlineDistanceEducation' : null } |
  { 'journalPublication' : null } |
  { 'fellowships' : null } |
  { 'awards' : null } |
  { 'careerCounselling' : null } |
  { 'prBranding' : null } |
  { 'admissionsGuidance' : null } |
  { 'doctoralExecutiveProgram' : null } |
  { 'universitySelection' : null } |
  { 'bookPublication' : null };
export type ProgramType = { 'law' : null } |
  { 'other' : null } |
  { 'arts' : null } |
  { 'medicine' : null } |
  { 'engineering' : null } |
  { 'business' : null } |
  { 'science' : null };
export type SubmitResult = { 'ok' : EnquiryId } |
  { 'err' : string };
export interface _SERVICE {
  'getEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'submitEnquiry' : ActorMethod<[EnquiryInput], SubmitResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];