/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EnquiryId = IDL.Nat;
export const InquiryType = IDL.Variant({
  'patents' : IDL.Null,
  'studyAbroad' : IDL.Null,
  'other' : IDL.Null,
  'thesisWriting' : IDL.Null,
  'onlineDistanceEducation' : IDL.Null,
  'journalPublication' : IDL.Null,
  'fellowships' : IDL.Null,
  'awards' : IDL.Null,
  'careerCounselling' : IDL.Null,
  'prBranding' : IDL.Null,
  'admissionsGuidance' : IDL.Null,
  'doctoralExecutiveProgram' : IDL.Null,
  'universitySelection' : IDL.Null,
  'bookPublication' : IDL.Null,
});
export const ProgramType = IDL.Variant({
  'law' : IDL.Null,
  'other' : IDL.Null,
  'arts' : IDL.Null,
  'medicine' : IDL.Null,
  'engineering' : IDL.Null,
  'business' : IDL.Null,
  'science' : IDL.Null,
});
export const EducationLevel = IDL.Variant({
  'highSchool' : IDL.Null,
  'other' : IDL.Null,
  'undergraduate' : IDL.Null,
  'postgraduate' : IDL.Null,
  'doctorate' : IDL.Null,
});
export const Enquiry = IDL.Record({
  'id' : EnquiryId,
  'inquiryType' : InquiryType,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'programType' : ProgramType,
  'educationLevel' : EducationLevel,
  'countryPreference' : IDL.Text,
});
export const EnquiryInput = IDL.Record({
  'inquiryType' : InquiryType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'programType' : ProgramType,
  'educationLevel' : EducationLevel,
  'countryPreference' : IDL.Text,
});
export const SubmitResult = IDL.Variant({ 'ok' : EnquiryId, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'submitEnquiry' : IDL.Func([EnquiryInput], [SubmitResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EnquiryId = IDL.Nat;
  const InquiryType = IDL.Variant({
    'patents' : IDL.Null,
    'studyAbroad' : IDL.Null,
    'other' : IDL.Null,
    'thesisWriting' : IDL.Null,
    'onlineDistanceEducation' : IDL.Null,
    'journalPublication' : IDL.Null,
    'fellowships' : IDL.Null,
    'awards' : IDL.Null,
    'careerCounselling' : IDL.Null,
    'prBranding' : IDL.Null,
    'admissionsGuidance' : IDL.Null,
    'doctoralExecutiveProgram' : IDL.Null,
    'universitySelection' : IDL.Null,
    'bookPublication' : IDL.Null,
  });
  const ProgramType = IDL.Variant({
    'law' : IDL.Null,
    'other' : IDL.Null,
    'arts' : IDL.Null,
    'medicine' : IDL.Null,
    'engineering' : IDL.Null,
    'business' : IDL.Null,
    'science' : IDL.Null,
  });
  const EducationLevel = IDL.Variant({
    'highSchool' : IDL.Null,
    'other' : IDL.Null,
    'undergraduate' : IDL.Null,
    'postgraduate' : IDL.Null,
    'doctorate' : IDL.Null,
  });
  const Enquiry = IDL.Record({
    'id' : EnquiryId,
    'inquiryType' : InquiryType,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'programType' : ProgramType,
    'educationLevel' : EducationLevel,
    'countryPreference' : IDL.Text,
  });
  const EnquiryInput = IDL.Record({
    'inquiryType' : InquiryType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'programType' : ProgramType,
    'educationLevel' : EducationLevel,
    'countryPreference' : IDL.Text,
  });
  const SubmitResult = IDL.Variant({ 'ok' : EnquiryId, 'err' : IDL.Text });
  
  return IDL.Service({
    'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'submitEnquiry' : IDL.Func([EnquiryInput], [SubmitResult], []),
  });
};

export const init = ({ IDL }) => { return []; };