/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type SubmitResult = {
    __kind__: "ok";
    ok: EnquiryId;
} | {
    __kind__: "err";
    err: string;
};
export interface EnquiryInput {
    inquiryType: InquiryType;
    name: string;
    email: string;
    message: string;
    phone: string;
    programType: ProgramType;
    educationLevel: EducationLevel;
    countryPreference: string;
}
export interface Enquiry {
    id: EnquiryId;
    inquiryType: InquiryType;
    name: string;
    submittedAt: bigint;
    email: string;
    message: string;
    phone: string;
    programType: ProgramType;
    educationLevel: EducationLevel;
    countryPreference: string;
}
export type EnquiryId = bigint;
export enum EducationLevel {
    highSchool = "highSchool",
    other = "other",
    undergraduate = "undergraduate",
    postgraduate = "postgraduate",
    doctorate = "doctorate"
}
export enum InquiryType {
    patents = "patents",
    studyAbroad = "studyAbroad",
    other = "other",
    thesisWriting = "thesisWriting",
    onlineDistanceEducation = "onlineDistanceEducation",
    journalPublication = "journalPublication",
    fellowships = "fellowships",
    awards = "awards",
    careerCounselling = "careerCounselling",
    prBranding = "prBranding",
    admissionsGuidance = "admissionsGuidance",
    doctoralExecutiveProgram = "doctoralExecutiveProgram",
    universitySelection = "universitySelection",
    bookPublication = "bookPublication"
}
export enum ProgramType {
    law = "law",
    other = "other",
    arts = "arts",
    medicine = "medicine",
    engineering = "engineering",
    business = "business",
    science = "science"
}
export interface backendInterface {
    getEnquiries(): Promise<Array<Enquiry>>;
    submitEnquiry(input: EnquiryInput): Promise<SubmitResult>;
}
import type { EducationLevel as _EducationLevel, Enquiry as _Enquiry, EnquiryId as _EnquiryId, EnquiryInput as _EnquiryInput, InquiryType as _InquiryType, ProgramType as _ProgramType, SubmitResult as _SubmitResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getEnquiries(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnquiries();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnquiries();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitEnquiry(arg0: EnquiryInput): Promise<SubmitResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEnquiry(to_candid_EnquiryInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SubmitResult_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEnquiry(to_candid_EnquiryInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SubmitResult_n18(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_EducationLevel_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EducationLevel): EducationLevel {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Enquiry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Enquiry): Enquiry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryType): InquiryType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ProgramType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProgramType): ProgramType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_SubmitResult_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmitResult): SubmitResult {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EnquiryId;
    inquiryType: _InquiryType;
    name: string;
    submittedAt: bigint;
    email: string;
    message: string;
    phone: string;
    programType: _ProgramType;
    educationLevel: _EducationLevel;
    countryPreference: string;
}): {
    id: EnquiryId;
    inquiryType: InquiryType;
    name: string;
    submittedAt: bigint;
    email: string;
    message: string;
    phone: string;
    programType: ProgramType;
    educationLevel: EducationLevel;
    countryPreference: string;
} {
    return {
        id: value.id,
        inquiryType: from_candid_InquiryType_n4(_uploadFile, _downloadFile, value.inquiryType),
        name: value.name,
        submittedAt: value.submittedAt,
        email: value.email,
        message: value.message,
        phone: value.phone,
        programType: from_candid_ProgramType_n6(_uploadFile, _downloadFile, value.programType),
        educationLevel: from_candid_EducationLevel_n8(_uploadFile, _downloadFile, value.educationLevel),
        countryPreference: value.countryPreference
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _EnquiryId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: EnquiryId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patents: null;
} | {
    studyAbroad: null;
} | {
    other: null;
} | {
    thesisWriting: null;
} | {
    onlineDistanceEducation: null;
} | {
    journalPublication: null;
} | {
    fellowships: null;
} | {
    awards: null;
} | {
    careerCounselling: null;
} | {
    prBranding: null;
} | {
    admissionsGuidance: null;
} | {
    doctoralExecutiveProgram: null;
} | {
    universitySelection: null;
} | {
    bookPublication: null;
}): InquiryType {
    return "patents" in value ? InquiryType.patents : "studyAbroad" in value ? InquiryType.studyAbroad : "other" in value ? InquiryType.other : "thesisWriting" in value ? InquiryType.thesisWriting : "onlineDistanceEducation" in value ? InquiryType.onlineDistanceEducation : "journalPublication" in value ? InquiryType.journalPublication : "fellowships" in value ? InquiryType.fellowships : "awards" in value ? InquiryType.awards : "careerCounselling" in value ? InquiryType.careerCounselling : "prBranding" in value ? InquiryType.prBranding : "admissionsGuidance" in value ? InquiryType.admissionsGuidance : "doctoralExecutiveProgram" in value ? InquiryType.doctoralExecutiveProgram : "universitySelection" in value ? InquiryType.universitySelection : "bookPublication" in value ? InquiryType.bookPublication : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    law: null;
} | {
    other: null;
} | {
    arts: null;
} | {
    medicine: null;
} | {
    engineering: null;
} | {
    business: null;
} | {
    science: null;
}): ProgramType {
    return "law" in value ? ProgramType.law : "other" in value ? ProgramType.other : "arts" in value ? ProgramType.arts : "medicine" in value ? ProgramType.medicine : "engineering" in value ? ProgramType.engineering : "business" in value ? ProgramType.business : "science" in value ? ProgramType.science : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    highSchool: null;
} | {
    other: null;
} | {
    undergraduate: null;
} | {
    postgraduate: null;
} | {
    doctorate: null;
}): EducationLevel {
    return "highSchool" in value ? EducationLevel.highSchool : "other" in value ? EducationLevel.other : "undergraduate" in value ? EducationLevel.undergraduate : "postgraduate" in value ? EducationLevel.postgraduate : "doctorate" in value ? EducationLevel.doctorate : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Enquiry>): Array<Enquiry> {
    return value.map((x)=>from_candid_Enquiry_n2(_uploadFile, _downloadFile, x));
}
function to_candid_EducationLevel_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EducationLevel): _EducationLevel {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_EnquiryInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnquiryInput): _EnquiryInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_InquiryType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): _InquiryType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ProgramType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProgramType): _ProgramType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inquiryType: InquiryType;
    name: string;
    email: string;
    message: string;
    phone: string;
    programType: ProgramType;
    educationLevel: EducationLevel;
    countryPreference: string;
}): {
    inquiryType: _InquiryType;
    name: string;
    email: string;
    message: string;
    phone: string;
    programType: _ProgramType;
    educationLevel: _EducationLevel;
    countryPreference: string;
} {
    return {
        inquiryType: to_candid_InquiryType_n12(_uploadFile, _downloadFile, value.inquiryType),
        name: value.name,
        email: value.email,
        message: value.message,
        phone: value.phone,
        programType: to_candid_ProgramType_n14(_uploadFile, _downloadFile, value.programType),
        educationLevel: to_candid_EducationLevel_n16(_uploadFile, _downloadFile, value.educationLevel),
        countryPreference: value.countryPreference
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InquiryType): {
    patents: null;
} | {
    studyAbroad: null;
} | {
    other: null;
} | {
    thesisWriting: null;
} | {
    onlineDistanceEducation: null;
} | {
    journalPublication: null;
} | {
    fellowships: null;
} | {
    awards: null;
} | {
    careerCounselling: null;
} | {
    prBranding: null;
} | {
    admissionsGuidance: null;
} | {
    doctoralExecutiveProgram: null;
} | {
    universitySelection: null;
} | {
    bookPublication: null;
} {
    return value == InquiryType.patents ? {
        patents: null
    } : value == InquiryType.studyAbroad ? {
        studyAbroad: null
    } : value == InquiryType.other ? {
        other: null
    } : value == InquiryType.thesisWriting ? {
        thesisWriting: null
    } : value == InquiryType.onlineDistanceEducation ? {
        onlineDistanceEducation: null
    } : value == InquiryType.journalPublication ? {
        journalPublication: null
    } : value == InquiryType.fellowships ? {
        fellowships: null
    } : value == InquiryType.awards ? {
        awards: null
    } : value == InquiryType.careerCounselling ? {
        careerCounselling: null
    } : value == InquiryType.prBranding ? {
        prBranding: null
    } : value == InquiryType.admissionsGuidance ? {
        admissionsGuidance: null
    } : value == InquiryType.doctoralExecutiveProgram ? {
        doctoralExecutiveProgram: null
    } : value == InquiryType.universitySelection ? {
        universitySelection: null
    } : value == InquiryType.bookPublication ? {
        bookPublication: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProgramType): {
    law: null;
} | {
    other: null;
} | {
    arts: null;
} | {
    medicine: null;
} | {
    engineering: null;
} | {
    business: null;
} | {
    science: null;
} {
    return value == ProgramType.law ? {
        law: null
    } : value == ProgramType.other ? {
        other: null
    } : value == ProgramType.arts ? {
        arts: null
    } : value == ProgramType.medicine ? {
        medicine: null
    } : value == ProgramType.engineering ? {
        engineering: null
    } : value == ProgramType.business ? {
        business: null
    } : value == ProgramType.science ? {
        science: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EducationLevel): {
    highSchool: null;
} | {
    other: null;
} | {
    undergraduate: null;
} | {
    postgraduate: null;
} | {
    doctorate: null;
} {
    return value == EducationLevel.highSchool ? {
        highSchool: null
    } : value == EducationLevel.other ? {
        other: null
    } : value == EducationLevel.undergraduate ? {
        undergraduate: null
    } : value == EducationLevel.postgraduate ? {
        postgraduate: null
    } : value == EducationLevel.doctorate ? {
        doctorate: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
